DATASET:
    BATCH_SIZE: 64

MODEL:
    CLASS_NAME: "MLP"
    WINDOW_SIZE: 1024
    HIDDEN_DIM: 256
    STRIDE: 300


OPTIMIZATION:
    LR: 0.00005
    NUM_EPOCHS: 10

EXPERIMENT_NAME: "mlp_health_index_estimation"
TASK: "health_index_estimation"
VERBOSE: True
DEVICE: "cpu"
