DATASET:
    BATCH_SIZE: 64
    VAL_RATIO: 0.15

MODEL:
    CLASS_NAME: "IE_SBiGRU"
    WINDOW_SIZE: 1024
    HIDDEN_DIM: 256
    NUM_LAYERS: 3
    FF_DIM: 256
    STRIDE: 300


OPTIMIZATION:
    LR: 0.00005
    NUM_EPOCHS: 10

EXPERIMENT_NAME: "wearcondition_health_index_estimation"
TASK: "health_index_estimation"
VERBOSE: True
DEVICE: "cpu"
SEED: 42
