DATASET:
    BATCH_SIZE: 64
    VAL_RATIO: 0.15

MODEL:
    CLASS_NAME: "Stacked_LSTM"
    WINDOW_SIZE: 1024
    STRIDE: 300
    NUM_LAYERS: 2
    DROPOUT: 0.2

OPTIMIZATION:
    LR: 0.00005
    NUM_EPOCHS: 10

EXPERIMENT_NAME: "wearcondition_health_index_estimation"
TASK: "health_index_estimation"
VERBOSE: True
DEVICE: "cpu"
SEED: 42
