DATASET:
    BATCH_SIZE: 64
    VAL_RATIO: 0.15

MODEL:
    CLASS_NAME: "TCM"
    WINDOW_SIZE: 1024
    HIDDEN_DIM: 256
    STRIDE: 300
    HIDDEN_DIM: 8
    NUM_LAYERS: 2


OPTIMIZATION:
    LR: 0.00005
    NUM_EPOCHS: 10

EXPERIMENT_NAME: "TCM_health_index_estimation"
TASK: "health_index_estimation"
VERBOSE: True
DEVICE: "cpu"
SEED: 42
