DATASET:
    BATCH_SIZE: 128
    VAL_RATIO: 0.15

MODEL:
    CLASS_NAME: "GSL_GNN"
    WINDOW_SIZE: 25
    STRIDE: 1
    THRESHOLD_LEVEL: 0.95
    ALPHA: 0.2

OPTIMIZATION:
    LR: 0.001
    NUM_EPOCHS: 10

EXPERIMENT_NAME: "gnn_anomaly_detection"
TASK: "anomaly_detection"
VERBOSE: True
DEVICE: "cpu"
SEED: 42
