DATASET:
    BATCH_SIZE: 128
    VAL_RATIO: 0.15

MODEL:
    CLASS_NAME: "AutoEncoderMLP"
    WINDOW_SIZE: 25
    STRIDE: 1
    HIDDEN_DIMS: [256, 128, 64]
    THRESHOLD_LEVEL: 0.95

OPTIMIZATION:
    LR: 0.001
    NUM_EPOCHS: 10

EXPERIMENT_NAME: "ae_anomaly_detection"
TASK: "anomaly_detection"
VERBOSE: True
DEVICE: "cpu"
SEED: 42
