DATASET:
    BATCH_SIZE: 64

MODEL:
    CLASS_NAME: "MLP"
    WINDOW_SIZE: 32
    HIDDEN_DIM: 256
    STRIDE: 1


OPTIMIZATION:
    LR: 0.00005
    NUM_EPOCHS: 10

EXPERIMENT_NAME: "mlp_remaining_useful_life_estimation"
TASK: "remaining_useful_life_estimation"
VERBOSE: True
DEVICE: "cpu"
