DATASET:
    BATCH_SIZE: 64
    VAL_RATIO: 0.15

MODEL:
    CLASS_NAME: "MLP"
    WINDOW_SIZE: 32
    HIDDEN_DIM: 512
    STRIDE: 1


OPTIMIZATION:
    LR: 0.0001
    NUM_EPOCHS: 35

EXPERIMENT_NAME: "mlp_remaining_useful_life_estimation"
TASK: "remaining_useful_life_estimation"
VERBOSE: True
DEVICE: "cpu"
SEED: 42
