DATASET:
    BATCH_SIZE: 128

MODEL:
    CLASS_NAME: "MLP"
    WINDOW_SIZE: 25
    HIDDEN_DIM: 256

OPTIMIZATION:
    LR: 0.001
    NUM_EPOCHS: 10

EXPERIMENT_NAME: "mlp_fault_daignosis"
TASK: "fault_diagnosis"
VERBOSE: True
DEVICE: "cpu"