DATASET:
    BATCH_SIZE: 128
    VAL_RATIO: 0.15

MODEL:
    CLASS_NAME: "TCN"
    WINDOW_SIZE: 25
    STRIDE: 1
    HIDDEN_DIM: 256
    KERNEL_SIZE: 5
    NUM_LAYERS: 4
    DILATION_BASE: 2
    DROPOUT: 0.2

OPTIMIZATION:
    LR: 0.001
    NUM_EPOCHS: 10

EXPERIMENT_NAME: "tcn_fault_daignosis"
TASK: "fault_diagnosis"
VERBOSE: True
DEVICE: "cpu"
SEED: 42
